feat: support transpose layout (patch)
InfiniTensor/RefactorGraph pull request #17
Opened 2023-10-23 09:09 UTC by bitzyz

support transpose layout：
![image](https://github.com/InfiniTensor/RefactorGraph/assets/93699316/f7ca423d-1180-4071-9a5b-6408b9f3ee80)

2023-10-23 14:14 UTC, YdrMaster requested changes

2023-10-23 14:14 UTC, YdrMaster commented on src/00common/include/common.h
> +    template<typename T> std::string vecToString(const absl::InlinedVector<T, 4> &vec) {
4 也应该是模板参数

2023-10-23 14:14 UTC, YdrMaster commented on src/00common/include/common.h
> +            ret.append(std::to_string(d));
`std::to_string` 能操作的类型少，反正是在造字符串，不如用 `stringstream` 或 `fmt::format`

2023-10-23 14:14 UTC, YdrMaster commented on src/04kernel/include/kernel/layout.h
> +                    return "NHWC ";
为什么有的有空格有的没空格？

2023-10-23 14:14 UTC, YdrMaster commented on src/05computation/src/transfomation/layout_permutation.cpp
> +        Shape shape = absl::InlinedVector<uint_lv2, 4>{N, H, W, C};
有个别名是 `Shape`

2023-10-24 02:10 UTC, bitzyz commented on src/00common/include/common.h
> +    template<typename T> std::string vecToString(const absl::InlinedVector<T, 4> &vec) {
已修改

2023-10-24 02:10 UTC, bitzyz commented on src/00common/include/common.h
> +            ret.append(std::to_string(d));
已修改

2023-10-24 02:10 UTC, bitzyz commented on src/04kernel/include/kernel/layout.h
> +                    return "NHWC ";
已修改

2023-10-24 02:10 UTC, bitzyz commented on src/05computation/src/transfomation/layout_permutation.cpp
> +        Shape shape = absl::InlinedVector<uint_lv2, 4>{N, H, W, C};
已修改

2023-10-24 02:21 UTC, YdrMaster commented
大差不差了，先合了再改改

2023-10-24 02:21 UTC, merged