Dev mem pool
InfiniTensor/RefactorGraph pull request #19
Opened 2023-10-25 06:35 UTC by kilinchange

- [ ] 添加可复用地址的 reusabal_allocator
- [ ] 添加一个偏移量计算器 offsetCalculator 供内存池和可复用地址的 allocator 使用
- [ ] 添加内存池 mem_pool

2023-10-25 08:43 UTC, YdrMaster requested changes

2023-10-25 08:43 UTC, YdrMaster commented on src/02mem_manager/include/mem_manager/mem_offset_calculator.h
> +        size_t getPeek();
拼错了，peak。推荐就叫 `peak`，不用加 `get`

2023-10-25 08:43 UTC, YdrMaster commented on src/02mem_manager/src/mem_offset_calculator.cc
> +        size = this->getAlignedSize(size);
要分别看一下要不要加 `this->`，一般不加

2023-10-25 08:46 UTC, YdrMaster requested changes

2023-10-25 08:46 UTC, YdrMaster commented on src/02mem_manager/include/mem_manager/mem_offset_calculator.h
> +        OffsetCalculator(size_t alignment);
似乎没有隐式转换的可能性……需要加 explicit

2023-10-25 08:54 UTC, kilinchange commented on src/02mem_manager/include/mem_manager/mem_offset_calculator.h
> +        size_t getPeek();
叫 peak 会和成员变量 peak 重名，编译时会报错。

2023-10-25 08:54 UTC, kilinchange commented on src/04kernel/src/graph.cc
> +        auto [size, offsets] = reusableAllocate(_internal, sizeof(uint64_t));
> `sizeof(uint64_t)` 是 8
这里参数的单位是 bytes

2023-10-25 09:10 UTC, kilinchange commented on src/02mem_manager/include/mem_manager/mem_offset_calculator.h
> +        // arguments：
fixed

2023-10-25 09:10 UTC, kilinchange commented on src/02mem_manager/include/mem_manager/mem_offset_calculator.h
> +        size_t getPeek();
fixed

2023-10-25 09:10 UTC, kilinchange commented on src/02mem_manager/src/mem_offset_calculator.cc
> +        size = this->getAlignedSize(size);
fixed

2023-10-25 09:11 UTC, kilinchange commented on src/02mem_manager/include/mem_manager/mem_offset_calculator.h
> +        OffsetCalculator(size_t alignment);
fixed

2023-10-25 09:42 UTC, YdrMaster requested changes

2023-10-25 09:42 UTC, YdrMaster commented on src/02mem_manager/include/mem_manager/mem_offset_calculator.h
> +        struct freeBlockInfo {
首字母大写啊大写

2023-10-25 09:42 UTC, YdrMaster commented on src/04kernel/src/allocator/reusable_allocator.cpp
> +                auto edgeIter = edgeToRefCount.find(inputIdx);
这个 find 出来的 it 为啥没用啊，后面又用 `operator[]` 取了

2023-10-26 01:53 UTC, kilinchange commented on src/02mem_manager/include/mem_manager/mem_offset_calculator.h
> +        struct freeBlockInfo {
fixed

2023-10-26 01:54 UTC, kilinchange commented on src/04kernel/src/allocator/reusable_allocator.cpp
> +                auto edgeIter = edgeToRefCount.find(inputIdx);
find 主要是为了判断 inputIdx 是不是在 edgeToRefCount 里，确实没必要特意创建一个 it 变量，改了

2023-10-26 02:09 UTC, kilinchange commented on src/04kernel/src/allocator/reusable_allocator.cpp
> +                auto edgeIter = edgeToRefCount.find(inputIdx);
fixed

2023-10-26 02:16 UTC, YdrMaster approved these changes

2023-10-26 02:16 UTC, merged