前端构图API
InfiniTensor/RefactorGraph pull request #69
Opened 2024-01-08 05:17 UTC by PanZezhong1725

2024-01-24 00:45 UTC, YdrMaster commented
比较多文件缺少尾随空行

2024-01-24 01:08 UTC, YdrMaster requested changes

2024-01-24 01:08 UTC, YdrMaster commented on src/09python_ffi/src/refactor_graph/frontend/transformer/attention.py
> +            attn_weights = self.matmul_group_k(query_states, key_states)
实际上全部使用 group matmul 的逻辑就行了，reshape 不产生计算，没有开销

2024-01-24 01:08 UTC, YdrMaster commented on src/09python_ffi/src/refactor_graph/frontend/transformer/attention.py
> +        attn_weights = self.div(
为什么这个不是 gemm 的 α？

2024-01-24 01:08 UTC, YdrMaster commented on src/09python_ffi/src/refactor_graph/frontend/transformer/attention.py
> +            attn_weights = self.cast(attn_weights, DTYPE.F32)
这里可以一直 cast，类型不变的 cast 会被跳过，不会计算

2024-03-01 06:58 UTC, closed without merging

2024-03-01 06:58 UTC, PanZezhong1725 commented
已转到独立repo：https://github.com/InfiniTensor/InfiniCanvas