[WIP] add max/min kernel
InfiniTensor/RefactorGraph pull request #84
Opened 2024-01-25 01:52 UTC by kilinchange

2024-01-30 06:53 UTC, kilinchange commented
![image](https://github.com/InfiniTensor/RefactorGraph/assets/44265800/f3041c56-6265-4ceb-be84-1d6ba17f44d1)
opt 模型端到端测试通过

2024-01-30 07:09 UTC, YdrMaster requested changes

2024-01-30 07:09 UTC, YdrMaster commented on src/04kernel/src/kernels/select/cpu_kernel.cc
> +        if (broadcaster.needBroadcast()) {
这里没必要判断吧，cpu 走不走坐标计算对性能的影响微乎其微

2024-01-30 07:09 UTC, YdrMaster commented on src/04kernel/src/kernels/select/cuda_kernel.cc
> +__device__ __forceinline__ static {dt} fn({dt} a, {dt} b) {{
判断大小用大于号小于号和三目运算符不用转型。直接内联进去就填一个大于号小于号就行了

2024-01-30 07:39 UTC, kilinchange commented on src/04kernel/src/kernels/select/cuda_kernel.cc
> +__device__ __forceinline__ static {dt} fn({dt} a, {dt} b) {{
fixed

2024-01-30 07:40 UTC, kilinchange commented on src/04kernel/src/kernels/select/cpu_kernel.cc
> +        if (broadcaster.needBroadcast()) {
广播与非广播不能合成一个逻辑

2024-01-30 07:52 UTC, kilinchange commented on src/04kernel/src/kernels/select/cpu_kernel.cc
> +        if (broadcaster.needBroadcast()) {
fixed

2024-01-30 09:41 UTC, YdrMaster commented
没改啊，没推上来？

2024-01-31 01:52 UTC, kilinchange commented
> 没改啊，没推上来？

现在改了

2024-01-31 02:01 UTC, YdrMaster approved these changes

2024-01-31 02:01 UTC, merged